/*
 * Portfolio gallery data — the single source of truth for portfolio.html
 * (full gallery) and the Portfolio teaser section on index.html.
 *
 * sites:   [label, url, screenshot file inside img/screenshot/]
 * designs: [file path relative to the site root, alt text]
 *
 * To add a website: drop its screenshot into img/screenshot/ and append a row.
 * Counts shown on both pages are computed from these arrays.
 */
window.PORTFOLIO = {
  sites: [
    ['zonov.ai', 'https://zonov.ai/home', 'screencapture-zonov-ai-dashboard-2026-08-11-10_37_44.png'],
    ['formidium.com', 'https://formidium.com/', 'screencapture-formidium-2025-08-01-07_41_24.png'],
    ['altsmarketplace.com', 'https://altsmarketplace.com/', 'screencapture-altsmarketplace-2025-08-01-07_41_48.png'],
    ['commonsubdoc.com', 'https://commonsubdoc.com/', 'screencapture-commonsubdoc-2025-08-01-07_42_32.png'],
    ['cryptobackoffice.com', 'https://cryptobackoffice.com/', 'screencapture-cryptobackoffice-2025-08-01-07_43_00.png'],
    ['cryptotax360.io', 'https://cryptotax360.io/', 'screencapture-cryptotax360-io-2025-08-01-07_44_05.png'],
    ['centroscolasticocarducci.it', 'https://centroscolasticocarducci.it/', 'screencapture-centroscolasticocarducci-it-2025-08-01-07_54_33.png'],
    ['kiwanja.net', 'https://kiwanja.net/', 'screencapture-kiwanja-net-2025-08-01-07_57_24.png'],
    ['alignmediation.co.uk', 'https://www.alignmediation.co.uk/', 'screencapture-alignmediation-co-uk-2025-08-01-08_01_28.png'],
    ['alignmediationtraining.com', 'https://www.alignmediationtraining.com/', 'screencapture-alignmediationtraining-2025-08-01-08_01_07.png'],
    ['TLV stem', 'TLV stem/index.html', 'screencapture-127-0-0-1-5500-TLV-stem-index-html-2025-08-01-08_01_43.png'],
    ['cryptofundtax.com', 'https://cryptofundtax.com/', 'screencapture-cryptofundtax-2025-08-01-07_44_45.png'],
    ['finalytic.com', 'https://finalytic.com/', 'screencapture-finalytic-2025-08-01-07_45_07.png'],
    ['hedgefundtax.com', 'https://hedgefundtax.com/', 'screencapture-hedgefundtax-2025-08-01-07_45_28.png'],
    ['ironbasecompliance.com', 'https://ironbasecompliance.com/', 'screencapture-ironbasecompliance-2025-08-01-07_45_48.png'],
    ['oneseamless.com', 'https://oneseamless.com/', 'screencapture-oneseamless-2025-08-01-07_46_19.png'],
    ['threealps.com', 'https://www.threealps.com/', 'screencapture-threealps-2025-08-01-07_54_49.png'],
    ['hsrevolution.com', 'https://hsrevolution.com/', 'screencapture-hsrevolution-2025-08-01-07_57_40.png'],
    ['uplogiks.co.uk', 'https://uplogiks.co.uk/', 'screencapture-uplogiks-co-uk-2025-08-01-08_00_25.png'],
    ['kmmonline.com', 'https://www.kmmonline.com/', 'screencapture-kmmonline-2025-08-01-08_00_45.png'],
    ['praxonomy.com', 'https://www.praxonomy.com/', 'screencapture-praxonomy-2025-08-01-07_46_47.png'],
    ['privateequityfundtax.com', 'https://privateequityfundtax.com/', 'screencapture-privateequityfundtax-2025-08-01-07_47_19.png'],
    ['privatefundadmin.com', 'https://privatefundadmin.com/', 'screencapture-privatefundadmin-2025-08-01-07_47_43.png'],
    ['plexponent.com', 'https://plexponent.com/', 'screencapture-plexponent-2025-08-01-07_48_02.png'],
    ['venetotech.it', 'https://venetotech.it/', 'screencapture-venetotech-it-2025-08-01-07_52_18.png'],
    ['commonconfidential.com', 'https://commonconfidential.com/', 'screencapture-commonconfidential-2025-08-01-07_55_51.png'],
    ['felicitysteadman.co.uk', 'https://felicitysteadman.co.uk/', 'screencapture-felicitysteadman-co-uk-2025-08-01-07_58_02.png'],
    ['cycysbakes.co.uk', 'https://www.cycysbakes.co.uk/', 'screencapture-cycysbakes-co-uk-2025-08-01-08_00_08.png'],
    ['deeplogix.co.uk', 'https://www.deeplogix.co.uk/', 'screencapture-deeplogix-co-uk-2025-08-01-07_59_52.png'],
    ['razorstate.com', 'https://razorstate.com/', 'screencapture-razorstate-2025-08-01-07_48_35.png'],
    ['seamlessalts.com', 'https://seamlessalts.com/', 'screencapture-seamlessalts-2025-08-01-07_49_03.png'],
    ['spvtax.com', 'https://spvtax.com/', 'screencapture-spvtax-2025-08-01-07_49_32.png'],
    ['venturefundtax.com', 'https://venturefundtax.com/', 'screencapture-venturefundtax-2025-08-01-07_51_25.png'],
    ['castlelake.com', 'https://www.castlelake.com/', 'screencapture-castlelake-2025-08-01-07_54_12.png'],
    ['ruislipblinds.co.uk', 'https://www.ruislipblinds.co.uk/', 'screencapture-ruislipblinds-co-uk-2025-08-01-07_57_06.png'],
    ['staff.allstar-aircon.co.uk', 'http://staff.allstar-aircon.co.uk/', 'screencapture-staff-allstar-aircon-co-uk-2025-08-01-07_58_42.png'],
    ['velocitymsc.com', 'https://velocitymsc.com/', 'screencapture-velocitymsc-2025-08-01-07_58_59.png'],
    ['adetiq.co.uk', 'https://www.adetiq.co.uk/', 'screencapture-adetiq-co-uk-2025-08-01-07_59_27.png'],
  ],
  designs: [
    ['img/hibru-template/חלק-עליון-ותחתוחן.jpg', 'Hebrew template design'],
    ['img/old-work/1.0 dark pms.png', 'PMS dark theme'],
    ['img/old-work/1.0 light pms.png', 'PMS light theme'],
    ['img/old-work/activities.png', 'Activities screen'],
    ['img/old-work/Add New Business.png', 'Add new business'],
    ['img/old-work/add new task.png', 'Add new task'],
    ['img/old-work/add notes.png', 'Add notes'],
    ['img/old-work/basic pms.png', 'Basic PMS'],
    ['img/old-work/business list.png', 'Business list'],
    ['img/old-work/business.png', 'Business'],
    ['img/old-work/chat.png', 'Chat UI'],
    ['img/old-work/dark pms.png', 'Dark PMS'],
    ['img/old-work/Web 1366 – 4.png', 'Web design 4'],
    ['img/old-work/jp-1.png', 'Design jp-1'],
    ['img/old-work/jp-2.png', 'Design jp-2'],
    ['img/old-work/light pms.png', 'Light PMS'],
    ['img/old-work/login page.png', 'Login page'],
    ['img/old-work/logo 1.jpg', 'Logo design 1'],
    ['img/old-work/logo 2 calibri.jpg', 'Logo design 2'],
    ['img/old-work/LOGOS.png', 'Logos'],
    ['img/old-work/notes.png', 'Notes'],
    ['img/old-work/main pms.png', 'Main PMS'],
    ['img/old-work/New Business.png', 'New business'],
    ['img/old-work/project list.png', 'Project list'],
    ['img/old-work/project.png', 'Project'],
    ['img/old-work/Repository.png', 'Repository'],
    ['img/old-work/screenshot-techspidies.com-2021.07.14-16_09_16.png', 'Techspidies design 1'],
    ['img/old-work/screenshot-techspidies.com-2021.07.14-16_10_26.png', 'Techspidies design 2'],
    ['img/old-work/screenshot-techspidies.com-2021.07.14-16_12_30.png', 'Techspidies design 3'],
    ['img/old-work/sub task page.png', 'Sub task page'],
    ['img/old-work/task list.png', 'Task list'],
    ['img/old-work/task.png', 'Task'],
    ['img/old-work/ui  2.jpg', 'UI design 2'],
    ['img/old-work/ui  4.jpg', 'UI design 4'],
    ['img/old-work/ui 3.jpg', 'UI design 3'],
    ['img/old-work/ui 5.jpg', 'UI design 5'],
    ['img/old-work/working time.png', 'Working time'],
    ['img/old-work/Web 1366 – 1.png', 'Web design 1'],
    ['img/old-work/Web 1366 – 2.png', 'Web design 2'],
    ['img/old-work/Web 1366 – 3.png', 'Web design 3'],
  ],
};
